# baseline_10: best
# config2_3: best
# congif2_4: best
# config2_5: best
# config2_7: [20, 40, 60, 80, 100, 120, 'best']
# tc_27 : ['best']
# tc_3: ['best']
# tc_4: [175]
# tc_5: ['best']
# tc_14: [200]
# tc_14: [200]
tc_14: [150]
# tc_14: [100]
# tc_15: ['best']
# tc_17: ['125']
# tc_18: [75]
# tc_19: [50]
# tc_20: ['best']
# tc_21: ['best']
